language: python
python:
- '2.6'
- '2.7'
- '3.5'
- '3.6'
install:
- pip install ansible
- git clone https://github.com/ansible/ansible.git
before_script:
- cd ansible && source hacking/env-setup && cd ..
- ansible --version
script:
- ansible-test compile --python $TRAVIS_PYTHON_VERSION

notifications:
  email:
    recipients:
      - anhubert@gmail.com
    on_success: never # default: change
    on_failure: always # default: always
