language: python
python:
- '2.7'
- '3.3'
- '3.4'
- '3.5'
- '3.6'
- 3.7-dev
- nightly
- pypy
- pypy3
install:
- pip install -r requirements.txt
before_script:
- cd ansible && source hacking/env-setup && cd ..
- ansible --version
script:
- ansible-test compile --python $TRAVIS_PYTHON_VERSION

notifications:
  email:
    recipients:
      - anhubert@gmail.com
    on_success: never # default: change
    on_failure: always # default: always
