language: python
python:
- '2.6'
- '2.7'
- '3.5'
- '3.6'
install:
- pip install ansible
- pip install git+https://github.com/sivel/ansible-testing.git#egg=ansible_testing
before_script:
- ansible --version
script:
- ansible-validate-modules ./
notifications:
  email:
    recipients:
      - anhubert@gmail.com
    on_success: never # default: change
    on_failure: always # default: always
